name: "Check for existence of a OCABundle.json file"

on:
  pull_request:
    types: [labeled, opened, synchronize, ready_for_review]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    #   - name: Check for file           
    #     id: file_check
    #     run: |
    #      if git status -s | grep -x "** OCABundle.json"; then
    #      echo "check_result=true" >> $GITHUB_OUTPUT
    #      else
    #      echo "check_result=false" >> $GITHUB_OUTPUT
    #      fi

    #   - name: Check if File exists
    #     if: steps.check_files.outputs.files_exists == 'true'
    #     # Only runs if all of the files exists
    #     run: echo All files exists!

      - name: "Check file existence"
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "OCABundles/**/OCABundle.json"

      - name: Commit files
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          npm install -g ajv-cli
          ajv validate -s OCABundles/validators/schema.json -d 'OCABundles/**/OCABundle.json'
    
    #   - name: Run dependent step
    #     if: steps.file_check.outputs.check_result == 'true'
    #     run: |
    #      npm install -g ajv-cli
    #      ajv validate -s OCABundles/validators/schema.json -d 'OCABundles/**/OCABundle.json'


