name: validate OCABundle.json on opened PRs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: opened

name: "File existence check"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        file: "OCAbundle.json"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
       # Only runs if all of the files exists
       run: echo All files exists!
    


