name: "Check for existence of a OCABundle.json file"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "OCABundle.json/${{ env.URL }}"

      - name: Check if File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
    
      - name: Run dependent step
        if: steps.file_check.outputs.check_result == 'true'
        run: |
         npm install -g ajv-cli
         ajv validate -s OCABundles/validators/schema.json -d 'OCABundles/**/OCABundle.json'


